# Describes the format for available Elexa Guardians services
disable_ap:
  description: Disable the device's onboard access point.
  fields:
    entity_id:
      description: The Guardian valve controller to affect.
    area_id:
      description: The area to affect.
enable_ap:
  description: Enable the device's onboard access point.
  fields:
    entity_id:
      description: The Guardian valve controller to affect.
    area_id:
      description: The area to affect.
reboot:
  description: Reboot the device.
  fields:
    entity_id:
      description: The Guardian valve controller to affect.
    area_id:
      description: The area to affect.
reset_valve_diagnostics:
  description: Fully (and irrecoverably) reset all valve diagnostics.
  fields:
    entity_id:
      description: The Guardian valve controller to affect.
    area_id:
      description: The area to affect.
upgrade_firmware:
  description: Upgrade the device firmware.
  fields:
    entity_id:
      description: The Guardian valve controller to affect.
    area_id:
      description: The area to affect.
    url:
      description: (optional) The URL of the server hosting the firmware file.
      example: https://repo.guardiancloud.services/gvc/fw
    port:
      description: (optional) The port on which the firmware file is served.
      example: 443
    filename:
      description: (optional) The firmware filename.
      example: latest.bin
